import { StyleSheet } from 'react-native';

/** Shared with the web app's palette, so the two products look like one thing. */
export const colors = {
  bg: '#0b1020',
  surface: '#151b32',
  surface2: '#1d2442',
  border: '#2c3558',
  text: '#eef1fa',
  textDim: '#a7b0cd',
  accent: '#6c8cff',
  mood: {
    '-2': '#e05c5c',
    '-1': '#e0925c',
    '0': '#8b93b0',
    '1': '#5cb5c4',
    '2': '#5cc48b',
  } as Record<string, string>,
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 16, paddingBottom: 48 },
  h1: { color: colors.text, fontSize: 22, fontWeight: '700', marginBottom: 4 },
  h2: { color: colors.text, fontSize: 16, fontWeight: '600', marginBottom: 4 },
  meta: { color: colors.textDim, fontSize: 13, lineHeight: 19 },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
  },
  moodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 },
  moodButton: {
    flexGrow: 1,
    flexBasis: 96,
    // 44pt: the minimum a thumb can hit reliably, which matters more here than on desktop.
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surface2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 8,
  },
  moodButtonText: { fontSize: 13, fontWeight: '500' },
  barRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 5, gap: 8 },
  barLabel: { color: colors.textDim, fontSize: 13, width: 84 },
  barTrack: {
    flex: 1,
    height: 16,
    backgroundColor: colors.surface2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: 4 },
  barValue: { color: colors.textDim, fontSize: 13, width: 44, textAlign: 'right' },
  statRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginVertical: 10 },
  stat: { minWidth: 96 },
  statN: { color: colors.text, fontSize: 20 },
  statK: { color: colors.textDim, fontSize: 11, letterSpacing: 0.5, textTransform: 'uppercase' },
  notice: {
    borderLeftColor: colors.accent,
    borderLeftWidth: 3,
    backgroundColor: colors.surface2,
    padding: 10,
    borderRadius: 8,
    marginVertical: 10,
  },
  noticeText: { color: colors.textDim, fontSize: 13, lineHeight: 19 },
  suppressed: { color: colors.textDim, fontSize: 13, fontStyle: 'italic' },
  primary: {
    backgroundColor: colors.accent,
    borderRadius: 8,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  primaryText: { color: colors.bg, fontWeight: '700', fontSize: 15 },
  tabBar: { flexDirection: 'row', borderBottomColor: colors.border, borderBottomWidth: 1 },
  tab: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: { borderBottomColor: colors.accent },
  tabText: { color: colors.textDim, fontSize: 14 },
  tabTextActive: { color: colors.text },
  deadline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    gap: 10,
  },
  statute: { color: colors.textDim, fontSize: 11 },
  breached: { color: colors.mood['-2'] },
});
